default_agent: entrypoint
agents:
  entrypoint:
    name: entrypoint
    entrypoint: entrypoint.py
    platform: linux/arm64
    container_runtime: finch
    aws:
      execution_role: arn:aws:iam::165361166149:role/None
      execution_role_auto_create: true
      account: '165361166149'
      region: us-west-2
      ecr_repository: None
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: false
    bedrock_agentcore:
      agent_id: null
      agent_arn: null
      agent_session_id: null
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    authorizer_configuration:
      customJWTAuthorizer:
        discoveryUrl: 'https://cognito-idp.us-west-2.amazonaws.com/us-west-2_bA0e3osFu/.well-known/openid-configuration

          '
        allowedClients:
        - 7ljspeqi6oeq43nrvkekh86lfc
    oauth_configuration: null
